const navToggle=document.querySelector('.nav-toggle');const nav=document.querySelector('.nav');if(navToggle&&nav){navToggle.addEventListener('click',()=>{const isOpen=nav.classList.toggle('open');navToggle.setAttribute('aria-expanded',String(isOpen));});document.querySelectorAll('.nav a').forEach(link=>{link.addEventListener('click',()=>{nav.classList.remove('open');navToggle.setAttribute('aria-expanded','false');});});}
const modal=document.querySelector('#project-modal');const modalBody=document.querySelector('#modal-body');const modalClose=document.querySelector('.modal-close');
const projects={
'baja-driver-model':{title:'Ergonomic Driver Model',category:'Baja SAE',hero:'assets/img/model_cad_iteration1.png',tags:['SolidWorks','Fusion 360','MeshLab','LiDAR Scans'],overview:'Created a driver modeling workflow to evaluate driver fit, cockpit clearance, and rule compliance for the Baja SAE vehicle.',sections:[{heading:'Purpose / Goal',body:'The goal was to convert scans of real drivers into usable CAD models so the team could validate cockpit packaging while checking clearance rules.'},{heading:'LiDAR Scan',body:'Driver scans were collected using Polycam and then cleaned so the scan geometry could be simplified and brought into CAD.'},{heading:'Scan to CAD',body:'The mesh was simplified in MeshLab, scaled using real body measurements, separated into limb segments in Fusion 360, and assembled in SolidWorks with joint-like motion.'},{heading:'Clearance Validation',body:'Transparent clearance shells were added around body segments to check rule compliance as the driver model moved inside the vehicle.'},{heading:'Result',body:'The workflow gave the team a repeatable method for evaluating multiple driver sizes and helped increase the viable driver range by approximately 15%.'}],gallery:['assets/img/model_cad_iteration1.png','assets/img/model_mechanism.gif','assets/img/model_refined_simulation.gif','assets/img/bracing.png']},
'baja-jig':{title:'Adjustable Ergonomic Jig',category:'Baja SAE',hero:'assets/img/Ergo_Jig_Andrew.jpg',tags:['SolidWorks','80/20','Driver Testing','Vehicle Ergonomics'],overview:'Designed and tested an adjustable physical jig for steering wheel and pedal placement experiments.',sections:[{heading:'Purpose / Goal',body:'The Baja vehicle needs to fit a wide range of drivers while maintaining comfort, agility, and rule-compliant clearances.'},{heading:'Design',body:'The jig concept uses adjustable steering and pedal placements so multiple drivers can test configurations before the final chassis geometry is locked.'},{heading:'Steering Adjustment',body:'The steering design focuses on angular, vertical, and fore-aft adjustability so arm comfort and leg clearance can be evaluated.'},{heading:'Pedal Adjustment',body:'The pedal setup allows forward/back adjustment and angle changes to compare comfort across different drivers.'},{heading:'Impact',body:'The jig connects CAD packaging decisions with real driver feedback, reducing guesswork in the ergonomics design process.'}],gallery:['assets/img/Ergo_Jig_Andrew.jpg','assets/img/Pedal.gif','assets/img/Steering.gif']},
'carbon-fiber':{title:'Carbon Fiber Seat + Steering Wheel',category:'Baja SAE',hero:'assets/img/CFcar.jpg',tags:['Carbon Fiber','Wet Layup','Vacuum Bagging','Manufacturing'],overview:'Manufactured composite Baja components using wet layup, vacuum bagging, trimming, finishing, and vehicle fitment.',sections:[{heading:'Purpose / Goal',body:'The team used carbon fiber to create lightweight driver-interface components while maintaining stiffness and durability.'},{heading:'Wet Layup',body:'The manufacturing process included mold preparation, fabric cutting, resin application, vacuum bagging, and curing.'},{heading:'Seat',body:'After curing, excess material was trimmed and the edges were finished for fit and safety.'},{heading:'Steering Wheel',body:'The steering wheel was cut and shaped from carbon fiber sheets, then finished for driver use.'},{heading:'Reflection',body:'This project gave me hands-on experience with a messy, tolerance-sensitive manufacturing process where preparation and process control matter.'}],gallery:['assets/img/CFcar.jpg','assets/img/CFseat.jpg','assets/img/CFsteering.jpg','assets/img/CFdrip.jpg']},
'rocket-bulkhead':{title:'Thrust Bulkhead',category:'Rocket Project UCLA',hero:'assets/img/bulk.png',tags:['SolidWorks','Structures','Fasteners','Hand Calculations'],overview:'Designed a rocket thrust bulkhead with attention to load transfer, bearing stress, fastener layout, and manufacturability.',sections:[{heading:'Engineering Problem',body:'The thrust bulkhead needed to interface with propulsion while transferring loads into the rocket structure.'},{heading:'Design Work',body:'The design balanced weight, manufacturability, thickness, fastener placement, and bearing stress constraints.'},{heading:'Manufacturing Constraint',body:'Because CNC machining was limited for the phase, the design needed to remain manufacturable with available processes.'}],gallery:['assets/img/bulk.png','assets/img/rocket.png']},
'robot-arm':{title:'3-DOF Robotic Arm Simulation',category:'Class / Technical Project',hero:'assets/img/matarm.jpg',tags:['MATLAB','Simscape','Inverse Kinematics','SolidWorks'],overview:'Built a simulated robotic arm using CAD import, inverse kinematics, and coordinate-based motion input.',sections:[{heading:'Objective',body:'Create a robotic arm model that could move toward user-defined coordinates using inverse kinematics.'},{heading:'Implementation',body:'The arm geometry was modeled in CAD, imported into Simscape Multibody, and connected to MATLAB motion calculations.'},{heading:'What I Learned',body:'This project strengthened my understanding of kinematics, coordinate transformations, and simulation-based prototyping.'}],gallery:['assets/img/matarm.jpg','assets/img/Sim.gif']},
'leg-drawers':{title:'Home Ergonomic Leg Drawers',category:'Class / Technical Project',hero:'assets/img/draw.png',tags:['SolidWorks','Simulation','Fabrication','Ergonomics'],overview:'Designed a discrete adjustable leg-rest drawer system to explore ergonomic positioning and home fabrication.',sections:[{heading:'Concept',body:'The idea was to create multiple drawer heights that could support different seated working positions.'},{heading:'CAD + Simulation',body:'The design used measured desk geometry, SolidWorks CAD, and a basic simulation study to check whether the structure was strong enough for expected use.'},{heading:'Manufacturing',body:'The prototype was built using available wood, a drill, and a handsaw, prioritizing function and learning over perfect craft.'}],gallery:['assets/img/draw.png','assets/img/desk.png','assets/img/drawers.png']},
'faraday-bed':{title:'Faraday Cage Bed',category:'Personal Project',hero:'assets/img/faraday.jpg',tags:['Prototyping','SolidWorks','Arduino','Shielding'],overview:'Designed and built a dorm-compatible Faraday cage bed prototype to test RF shielding, blackout performance, airflow, and sleep discipline.',sections:[{heading:'Motivation',body:'I wanted a physical system that made my sleep environment more controlled by reducing light, distractions, and wireless signal exposure near the bed.'},{heading:'Constraints',body:'The design needed to be removable, dorm-safe, inexpensive, ventilated, and compatible with an existing bed frame.'},{heading:'Build',body:'The prototype used shielding material, blankets, frame elements, hinges, and airflow considerations under real dorm constraints.'}],gallery:['assets/img/faraday.jpg','assets/img/faraday.gif','assets/img/Bed_assem.jpg','assets/img/meonbed.jpg']},
'website':{title:'Portfolio Website',category:'Personal Project',hero:'assets/img/website.jpg',tags:['HTML','CSS','JavaScript','GitHub Pages'],overview:'A personal engineering portfolio for presenting projects, documentation, resume material, and project photos.',sections:[{heading:'Purpose',body:'The site is meant to help recruiters quickly understand my strongest engineering work while still preserving detailed project documentation.'},{heading:'Design Direction',body:'The redesign prioritizes project cards, grouped categories, clean typography, expandable project documentation, and a clearer resume/contact path.'}],gallery:['assets/img/website.jpg']}
};
const currentProjects={
'water-bottle':{title:'Water Bottle Auto-Fill System',category:'Current Project',progress:'20%',overview:'Servo-actuated faucet controller for automatically filling a water bottle through repeatable timed cycles.',sections:[{heading:'Goal',body:'Create a simple, repeatable setup that fills the bottle with one button press while accounting for the RO system flow slowing down over time.'},{heading:'Current Status',body:'Planning the actuation mechanism, mapping faucet motion, and preparing CAD work. More useful prototyping begins once the servo motors arrive.'},{heading:'Next Steps',body:'Measure fill timing, design the servo linkage, create a bottle/faucet alignment jig, and later 3D print the housing.'}]},
'busy-indicator':{title:'Busy Indicator',category:'Current Project',progress:'10%',overview:'A small visible indicator system to show when I am busy, recording, studying, or should not be interrupted.',sections:[{heading:'Goal',body:'Build a simple physical status display that communicates availability clearly.'},{heading:'Current Status',body:'Concept stage. Main decisions are display type, enclosure style, and whether it should use buttons, LEDs, or wireless control.'}]},
'blinds':{title:'Automated Blinds',category:'Current Project',progress:'5%',overview:'Motorized blinds project for controlling room light automatically or with a simple user input.',sections:[{heading:'Goal',body:'Create a compact mechanism that can open and close blinds reliably without permanently modifying the apartment.'},{heading:'Current Status',body:'Early concept stage. Need to inspect the blind geometry and decide between servo, stepper, or geared DC motor actuation.'}]},
'umbrella-robot':{title:'Umbrella Robot',category:'Current Project',progress:'5%',overview:'Mobile robot concept that could carry or position an umbrella to provide shade or rain coverage.',sections:[{heading:'Goal',body:'Explore a small wheeled robot platform with a mounted umbrella and basic stability/control constraints.'},{heading:'Current Status',body:'Idea stage. Needs early sketches, load/stability estimates, and drivetrain concept selection.'}]}
};
function sectionMarkup(sections){return sections.map(section=>`<section class="modal-section"><h3>${section.heading}</h3><p>${section.body}</p></section>`).join('');}
function galleryMarkup(gallery,title){if(!gallery||gallery.length===0)return '';return `<section class="modal-section"><h3>Project Images</h3><div class="modal-gallery">${gallery.map(image=>`<img src="${image}" alt="${title} image">`).join('')}</div></section>`;}
function openProject(projectId){const project=projects[projectId];if(!project||!modal||!modalBody)return;modalBody.innerHTML=`<article><div class="modal-hero"><p class="eyebrow">${project.category}</p><h2>${project.title}</h2><p>${project.overview}</p><div class="modal-meta">${project.tags.map(tag=>`<span>${tag}</span>`).join('')}</div><img src="${project.hero}" alt="${project.title}"></div>${sectionMarkup(project.sections)}${galleryMarkup(project.gallery,project.title)}</article>`;openModal();}
function openCurrentProject(projectId){const project=currentProjects[projectId];if(!project||!modal||!modalBody)return;modalBody.innerHTML=`<article><div class="modal-hero"><p class="eyebrow">${project.category}</p><h2>${project.title}</h2><p>${project.overview}</p><div class="modal-meta"><span>${project.progress} complete</span><span>In progress</span></div><div class="modal-callout"><strong>Progress:</strong> ${project.progress}</div></div>${sectionMarkup(project.sections)}</article>`;openModal();}
function openModal(){modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-locked');}
function closeModal(){if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-locked');}
document.querySelectorAll('.project-open').forEach(card=>card.addEventListener('click',()=>openProject(card.dataset.project)));document.querySelectorAll('.current-open').forEach(card=>card.addEventListener('click',()=>openCurrentProject(card.dataset.current)));if(modalClose)modalClose.addEventListener('click',closeModal);if(modal)modal.addEventListener('click',event=>{if(event.target===modal)closeModal();});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&modal&&modal.classList.contains('open'))closeModal();});
